---
name: ((deployment_name))

instance_groups:
- name: redis
  azs: [((default_az))]
  instances: ((node_count))
  vm_type: ((default_vm_type))
  stemcell: default
  persistent_disk_type: ((default_persistent_disk_type))
  networks:
  - name: ((default_network))
  jobs:
  - name: redis
    release: redis-service
    properties:
      bind: ((redis_bind))
      password: ((redis_password))
      tls: ((redis_tls))
      tls_keys: ((redis_keys))
      maxmemory: ((redis_maxmemory))
      maxmemory_policy: ((redis_maxmemory_policy))
  - name: redis_check
    release: redis-service
  - name: redis_broker-1.5
    release: redis-service
    properties:
      bind: ((redis_bind))
      password: ((redis_broker_password))
      loglevel: ((redis_broker_loglevel))
  - name: redis_broker_check-1.5
    release: redis-service
  - name: redis_exporter
    release: redis-service
    properties:
      tls_keys: ((exporter_keys))
      debug: ((redis_exporter_debug))

variables:
- name: redis_password
  type: password
- name: redis_broker_password
  type: password
- name: redis_ca
  type: certificate
  options:
    common_name: ((deployment_name))
    organization: 'orange.com'
    key_length: 8192
    duration: 365
    is_ca: true
    self_sign: true
- name: redis_keys
  type: certificate
  options:
    ca: redis_ca
    common_name: 'Server'
    organization: 'orange.com'
    key_length: 4096
    duration: 365
- name: exporter_keys
  type: certificate
  options:
    ca: redis_ca
    common_name: 'Exporter'
    organization: 'orange.com'
    key_length: 4096
    duration: 365

stemcells:
- alias: default
  os: ((stemcell_os))
  version: "((stemcell_version))"

releases:
- name: redis-service
  version: latest

update:
  canaries: 2
  canary_watch_time: 30000-60000
  max_in_flight: 2
  update_watch_time: 30000-60000
  serial: false
