---
name: ((deployment_name))

instance_groups:
- name: sentinel-master
  azs: [((default_az))]
  instances: ((master_node_count))
  vm_type: ((default_vm_type))
  stemcell: default
  persistent_disk_type: ((default_persistent_disk_type))
  networks:
  - name: ((default_network))
  jobs:
  - name: redis_sentinel
    release: redis-service
    provides:
      redis_sentinel_conn: {as: ((shared_sentinel_master)), shared: true}
    consumes:
      redis_sentinel_conn: {from: ((shared_sentinel_master))}
    properties:
      bind: true
      port: '0'
      password: ((redis_sentinel_password))
      tls: true
      tls_dh_length: ((redis_dh_length))
      tls_replication: true
      tls_keys:
        certificate: |
          -----BEGIN CERTIFICATE-----
          MIIEDDCCAfQCFGusl0TjbsYRkOhMhkP+fDlkgGhYMA0GCSqGSIb3DQEBCwUAMDkx
          EzARBgNVBAoMCm9yYW5nZS5jb20xIjAgBgNVBAMMGXJlZGlzLXNlbnRpbmVsLXNo
          YXJlZC10bHMwHhcNMjAwOTEwMTExOTMyWhcNMjEwOTEwMTExOTMyWjBMMRMwEQYD
          VQQKDApvcmFuZ2UuY29tMSIwIAYDVQQLDBlyZWRpcy1zZW50aW5lbC1zaGFyZWQt
          dGxzMREwDwYDVQQDDAhTZW50aW5lbDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCC
          AQoCggEBALLeB71xFP0eEaNw0gn+j0SyuIJbuGJ6U2iWEBTchTd7ghc8Ntk1oyKM
          RkxCvc77TrXMitYq3Q6KEQE3nr3jt4BhxciiHSnhwsNNvXmOzXqFjCgX4l/WpOsN
          FjJgopd2uCd8Yh6KBH38lW7+pyS0/7r81TgnS8kMkTlvKGuxh/3GcdtQZeOSHxY2
          1J20ZN7nFghjgJ5T6k7GqXzWFXgr3oAkqs8dHEitogHFQuzOtLoAdrpFrf5Pm0tU
          Mcg3DAnCl/Mdn07NF/EVvFIfiZX/haiSI5os1HUXSbOfE7l4600wsZT1YGt13CG/
          EyOQSHCLUsc37o+d5GT5qmKeUZYxsZ8CAwEAATANBgkqhkiG9w0BAQsFAAOCAgEA
          i/J4KGp6Wuf5deQbau4+5SVnRjgBoMzjnODPAiUWORZK9XClhze+xrxtB6g6Q2P6
          kO12VHZgQCk/0l0Q0KMzCHvHAtLyHXdCBtksRzWGx4Fv2dE2dDqDdEwkuVt1kBoU
          1Q0AbKiBZHHzvhzkfbnCP9QD5RmCclBFsCnJXavp4PWWgS6w0AN8lNyjqswfTnT/
          CXMEvLBQrI8kJTIKN7nZ/zA4//1d/qnTUOBopevu86B6KjkmucSCVtHiPwmbyndV
          o/4L5ajD0xreyK0fS0BiPg7MertwHidZ0HXUn9GnYt6UOAn3+o/VT0A46GYh70Y4
          nb3CviSaUssrEgK7nQQxYVaYRuYVVEaHf8ys1rnuFYfKuR6hRxZ6AAg7pIWQCYcl
          9uIHdciGP5hjxjVvGfNSuSagomFGyRQgjitf63Qp/sMnYk1JWMfXR47cXgu2Ik+f
          2e1m8l6+EpFvbpEj/vMavMn2gbjvrQ8Sdg6An0bC1GyH90qjugYmGKmM1dtZL/dv
          PCs7Psy38CvF8yXBLwx9TOmjsJEkrQMOCr+TMLS2SS2PRNQK2G6Z5o+ozs+ifRXV
          xj9J9YXINx2fnB9A+3aa365Uvo0/1FcNMYrxAkmZFGmdDxm+kr+SS0hHYHTlFH3Q
          EX1Vfu8VS89Iomus7sXa2MgaxrhcI2683yBHskxBJsU=
          -----END CERTIFICATE-----
        private_key: |
          -----BEGIN RSA PRIVATE KEY-----
          MIIEogIBAAKCAQEAst4HvXEU/R4Ro3DSCf6PRLK4glu4YnpTaJYQFNyFN3uCFzw2
          2TWjIoxGTEK9zvtOtcyK1irdDooRATeeveO3gGHFyKIdKeHCw029eY7NeoWMKBfi
          X9ak6w0WMmCil3a4J3xiHooEffyVbv6nJLT/uvzVOCdLyQyROW8oa7GH/cZx21Bl
          45IfFjbUnbRk3ucWCGOAnlPqTsapfNYVeCvegCSqzx0cSK2iAcVC7M60ugB2ukWt
          /k+bS1QxyDcMCcKX8x2fTs0X8RW8Uh+Jlf+FqJIjmizUdRdJs58TuXjrTTCxlPVg
          a3XcIb8TI5BIcItSxzfuj53kZPmqYp5RljGxnwIDAQABAoIBAEPNjKuQUT9+BXuq
          ScSGHbMR+IVZ1XRnIHUV5XSy/0C/7dl29uexwGxZNlC0QBVVCEo8BikXSIK5babD
          ecZLqwTci0f5xApbTSQRtRB+RH/8XdvY6fQgfpWneVGRdjDqTPaS3PLsqLVFaTQR
          DjUI86PjMcQ+iSjmParC61SfkIhu7b9obN7hzk4RRAj676O3NRuEEhKsUPXRwq8o
          mfAtlr15D0jZjUut0iVbrRSoszz9l9lrh3nclFrM0tMwEJsy9IFTwblO2WCaLE3L
          RIlymFLx+p+BLnOnjrs/NQGOAmvx9+tmjqar+UcFSLN7o/rHMqS2yQxvoH2fVm+J
          qHZ4pWkCgYEA4kt+vOxarwKa9ci2QNp+IMQoqXY0xHe6nu8Ri/qJzvGyBj+KGmse
          lGaLzTCUxSVnB/yjzNbddmJZ/aYqSYqi5G+0vzJh9dl3CNDrEMd9XH7oZgDYy115
          WZ8wLxnDY1Qunczd3jZYs0mG2ISopkVRs2itbJJaN2v3BrB3+giYQtsCgYEAyljC
          VYPT5HBQgtGVCVoq2neBF4hs7ntRPhQDvCFhPBJ5T/2xLZC8Z++E0vVjiXwLgeWm
          5iM1xuVw5a7gDLqgtX/M4dTLeaWSbeLrLm4giUozxDMDyGlIHb305zvA00pRjxWB
          mFmWDhKxb5bfuZjypk4m8jHvYkVxMBQLKH17TY0CgYAeURbtoIyVnbe87eLc1WjI
          Yv8/lMKE/7VUzZqAMlR8EQ1UoPaTi35RS1u3ZabIsrYW79XR/4cz8QE1ZimMKLKi
          AAUrCEjvcu7rk3Gqkc9NsQLZh4uD00YKp7UA2ma+y+xi36tptcY0XsleAIfHnsnP
          S1rQjNrhSemST9oC+VvMuQKBgDVviSqCHMP38RsK89u7ZxO4eWvYiEPWZxcIvA/D
          lOUDT+wS5+ZLkaW0+BOp3/Zfvr44AoJGDB6RWuYc72gNJQGpVVbSFkXytp+0TD0/
          sfHvmYoXmskjHHtWPcWO3xYtSyqJGGc+SUVAJIF+i2h8/p9yhhBxpXEDO6fhsyyn
          LpfFAoGAcXfK6hqn4BJlrBBlvsTi2Itog7WqxIDK38LXeTeae7ecAtZLyWZLUwAV
          f1WZ7VMHNz0DbPMIVyGz/ryE0aO5KEoG6T1Jr7d76NJF/dXADYW2iBSsQGZ68i3I
          mbiFhM/YbyeJI7NP7Gc4Be0U6r3Ac5vXrkBfVFCfkB1t9VYylsM=
          -----END RSA PRIVATE KEY-----
        ca: |
          -----BEGIN CERTIFICATE-----
          MIIFUzCCAzugAwIBAgIUGfpxaumpt2PF62TT2fDJV5DvfH0wDQYJKoZIhvcNAQEL
          BQAwOTETMBEGA1UECgwKb3JhbmdlLmNvbTEiMCAGA1UEAwwZcmVkaXMtc2VudGlu
          ZWwtc2hhcmVkLXRsczAeFw0yMDA5MTAxMTE5MzFaFw0zMDA5MDgxMTE5MzFaMDkx
          EzARBgNVBAoMCm9yYW5nZS5jb20xIjAgBgNVBAMMGXJlZGlzLXNlbnRpbmVsLXNo
          YXJlZC10bHMwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQC/Fkl+u4iU
          Hv3FpHnQoGVQE8p+vuPYorECZ6T2AjN+o0cGERuKIqGxNoxN3keltcCtN451fvid
          K9j3epDUPp3RRKoqInqq+uQtwLpUXexdpmnYJ8uZUdc8jSzrc0gv9uZetw/tHNBU
          CGKKwd44+Q5Zet9QPglsQvOKU/cZEUCw+a3ORzXzelXxr3nuMbBUyUQtUpqpHDEl
          QViddjjTBDCmVpP6grYsyteHzVoL6k5kDf+2V7kssQbDepCWsqjKhz+Tkaa3bPq1
          iIpIIFDAYK+HX3lIFYrPrBobd0e47He1qSAzxoGCWyNzqciukzKB5KT5E5/LybNx
          v4rH84xIkRZGViA/P0AgM4NmfjTCA/RizU8C9VJQc9lwsV9GftiG0Rd2ooL9sI6E
          bY9QKbo5qlw3EBwsjcXHM1zGQXBM6/Ps1f83Cr73E/jlzPvyWBm7FBz/NNepy6Gp
          MClZWp7BF1+O68dpF07uZF0GheAPhup2eRoDBIA3XzEzfcnbbFwGu4mUEOmhQSC5
          TUxIKUUyvt+GBJxOtbgxnqc/teTuHdGQM31nMfLO5cI+xlymBB47qyjxww7NjXiP
          jwCvtFwNE79SNYlGxQHGhY2vKEr8lPhfauFQvdIGmGQUhdf6vU/9ppErBzvz7aPN
          IC0xn53Zl+DyTIwQhCdMxT1LUzfOtSLw9wIDAQABo1MwUTAdBgNVHQ4EFgQUo9s4
          8M+ZGMEYFzxONvBxDuNsXBMwHwYDVR0jBBgwFoAUo9s48M+ZGMEYFzxONvBxDuNs
          XBMwDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAgEAi3ZvWAsMly9y
          2xHNwc7KfUGN2nSK6ssCwnz+Ni9lAGbHzn0/byqfnfT0pghqtfp7mD0sYvpkKv9+
          iI47hKoJ7xwcvKXGnWORBHMqEIdiZwxynm+w06/NU1bDfYyt1YZkqiAxIoYu6EUS
          ItyDBsSM/2DYNsv+OyF5zyhH9MjPdSGORW4TWrED00JiydRXV9Q3vDb1SW+o6CDO
          /PWitlgY3ssMmKmrFaQzCvv/Y/w4WMyyywty6+vnXcO1KXyDfCB2MnjEe326CAtZ
          2LsxCRUOJdDqTjEreDuXbBmiOsI1m9p1UYihHbQCuWVV10vGlU0+rLn19PTne6BS
          F9EOsMoTzkd+5OUK09H18Fw677fONpZ0PeufJSLE3BM8OsoYVaCRPsFsnJst9VH4
          BWYoSsIQYOFav9zA4u55jnrNkKFt6moaIrtkuqJKDOUTnnkAUDwjTn+QN22OcRmH
          Eyh4E2hdyTPYM1csPOSkMsOleNMohxk+1oXCWswMeqvTe5zeNPdJ5+ogoZS7j7tm
          IGNHgNcC5Wfi2eT+fKsDdKBCgeK+XMTmOjUtRle+h+Q3O7T74U5NexVrHf+R10K7
          DflJPxUrSbxH0phFgxqKFykhcQfEXzLan/th+B1cnp2+y2kIpNpkxUnRGAh+iKtL
          PTDhxGQ3hAlmpK4bZK8DXEBYIsiGRCM=
          -----END CERTIFICATE-----
- name: sentinel-slave
  azs: [((default_az))]
  instances: ((slave_node_count))
  vm_type: ((default_vm_type))
  stemcell: default
  persistent_disk_type: ((default_persistent_disk_type))
  networks:
  - name: ((default_network))
  jobs:
  - name: redis_sentinel
    release: redis-service
    provides:
      redis_sentinel_conn: {as: ((shared_sentinel_slave)), shared: true}
    consumes:
      redis_sentinel_conn: {from: ((shared_sentinel_master))}
    properties:
      tls_dh_length: ((redis_dh_length))
      tls_keys:
        certificate: |
          -----BEGIN CERTIFICATE-----
          MIIEDDCCAfQCFGusl0TjbsYRkOhMhkP+fDlkgGhZMA0GCSqGSIb3DQEBCwUAMDkx
          EzARBgNVBAoMCm9yYW5nZS5jb20xIjAgBgNVBAMMGXJlZGlzLXNlbnRpbmVsLXNo
          YXJlZC10bHMwHhcNMjAwOTEwMTEyMDM0WhcNMjEwOTEwMTEyMDM0WjBMMRMwEQYD
          VQQKDApvcmFuZ2UuY29tMSIwIAYDVQQLDBlyZWRpcy1zZW50aW5lbC1zaGFyZWQt
          dGxzMREwDwYDVQQDDAhTZW50aW5lbDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCC
          AQoCggEBAJYjzuomxMXvOIRCDwqcxPfxhhAcylYS2+TIgg+5UeyYlvIsc/xLvdp8
          CIQ6B3B2tBiC/3WyKfOeZHEDKkhNXs0z/AoMficO02Px06i5xiY+hB+CgXPsw0gN
          FX8KWSibByALEnx/mL5p/OmoIy+4Sjz8TNdIZsdBffVcGgEe+uMilBWWhviyaiah
          X4usNLzTQCgugJqTjYKBW2OyG5Sr+UUYYcjQ9FnAiScKmCw2UDd/4VF1Rk/H9c38
          2eYKVJZcHjye72IOa99Rtg/FNFUVTv1zn4SXOeA1N6ig2prjZM1AhaTaMLn2y6m3
          upUmsA0eoQBSD0Nb0eDg1EZe++57EKkCAwEAATANBgkqhkiG9w0BAQsFAAOCAgEA
          Mcv6qbxJfw7p39T8p03R6EL+wb/B8rMzrv7nERFo/6+BXOohukai9rx7QtEhdlOc
          t2E6DRFbQ0/QYWCr0dVLSCOirNlix/cy1HhYqhia28H06uawg8sCF2HtlQVMUJV/
          s1np9QMazRKbogmmW59wySpZF7qBAQu0soBx3JttdszNCaZHC1SSzTUChzOFj42A
          nrIvhRxzN6LX8Ey8VY7sb12vXZ4X/3z1B7gfVUtadMywR3vROgDAyl2rFPa4JXN2
          7T0EFiqZmF+UIvG366tg5wsVTlgsb/biGRHZzP3RCWigLxQENxeVdAxRRNXvq0lR
          +RuOOiuC8h9A0IPUIFlRTeOuSk/ESoS5OalNZhzJUTyEWZwHH5vPPOxN9MVNFOz1
          8V50Mn+WwHN/LNEy1AholN4z05+8wQLF5m5IhvOBdMy31sbuWG8tY8WJXcbk2UPF
          gMsa3KzKp1NTFBSgTSnD6CeBqQYk6Tb3XcCLBo3uEW1AdmytnE7OwQyeliOSBj21
          vfQPGLINBugadC/8m248NYc1bp6oHDR7kFml721ZFUuJpwHkmTv9V4+II/zaha8b
          as3Ybdw1XhSMEnFFiW/1N+dN1T9ZQYYaf9/MrUw+u2E8Mb5L+U1Ds8/o1nKStNin
          dpqqmtd3oSHsPI4hBsZc23c87HSeD26opPNK7FvfNqo=
          -----END CERTIFICATE-----
        private_key: |
          -----BEGIN RSA PRIVATE KEY-----
          MIIEogIBAAKCAQEAliPO6ibExe84hEIPCpzE9/GGEBzKVhLb5MiCD7lR7JiW8ixz
          /Eu92nwIhDoHcHa0GIL/dbIp855kcQMqSE1ezTP8Cgx+Jw7TY/HTqLnGJj6EH4KB
          c+zDSA0VfwpZKJsHIAsSfH+Yvmn86agjL7hKPPxM10hmx0F99VwaAR764yKUFZaG
          +LJqJqFfi6w0vNNAKC6AmpONgoFbY7IblKv5RRhhyND0WcCJJwqYLDZQN3/hUXVG
          T8f1zfzZ5gpUllwePJ7vYg5r31G2D8U0VRVO/XOfhJc54DU3qKDamuNkzUCFpNow
          ufbLqbe6lSawDR6hAFIPQ1vR4ODURl777nsQqQIDAQABAoIBADqTk+nU4FadI36u
          SzIHwe0+ZOCqauK0DuiutdeupODbE6E+aK4ZWuQAGk6EWVyuY0tg6Iwhy65JsMRK
          yNdWoFMNIhtFjn5skVrgAYVFnaJUJ7Ync5wn1nSo7icXgXuPKHN+/mJmYdCAh3Ud
          7URz8Trj8JLZo4e/7IWqvlaLoLS2svBr4AwbhIZ6E4qfUEvfRJnvMfiBqYziwxZZ
          kn6C9+Pfh+f1bJV3fvKLYVwLKCVd9r6m1fxPCe28Jy5faRli1IKcUXJgR4/Vbgf/
          i4oZbE9qQWaUYGFFAl38iK397ndavNs0NFVZH1X/pDaIz1LLMsQZR1Z6u9QbaLaX
          vejXr1ECgYEAx7not91Hyo7cKSN/GLnDEL6CcbFW2ho5LOoWkOpSimHtXhAMKFwG
          0yVzVhd7glq6w/qfAcnZRQIf0lM/fv4stpWDPKWpH7nj26W2aVAe1R+bNZmERFEl
          EF5JE1R0mnPAPSnLkxoViLpVUe/E3NcjTPX8sM+AeWjh3IV81pbJJZUCgYEAwHFG
          5lNMa6Zm7ZyfBKbdredoCW1rvLkgcZXOHU1aI9aMbLlYnEOwecNKyVcszOA+Ous7
          GniGodm6uAgmBSJSuox6SDrhsE5tyNGWXzE/LhOQlB76qQJ6nbQumhXMOp9p6feB
          1wIspVpiW0nAPaTKbGgqqbIznACJ98iRcXBZUcUCgYBgwAMmxi+XxPqLhyFzVdFT
          lCXWc2SyRI+73S3PR2Nym5uDvFxXVLUNpY+ofbmb3N2qQAa0tBXm4u+NUDxrBS+d
          xvGK+Gjj8IWbijvB6kj1Ttk97r7u5SwCMNpPXdMaWsYeGtf9y13xHOplxbNkk2cL
          SgH9mJcQuSjoTVW7EdIgvQKBgH2K6Jfli5tGySsF2+9q9H840XQk//30P6gZ9IbF
          KaLrmlxrZdU7i2tD7gv/ZOia+b3yK3KPYjVAF0Frf3Il/BZbAoMQdp9P6urxX8nm
          FLN4a/9VXmzXgypSm3xF8B/mU3Ag2YFsl7efiT7IlDMiyDOEmSBvcp+48kjFfayl
          gH+JAoGAZ6vjjFs7VCn6kVfX2Ux0UK90arYJxfKVqBA/AujM4WkAqnK/JVc9h7cp
          /1s1FDEM4Q+CAF0WQaG6ttw9ZKTfPf0UfxtmS7lVp1OBVgAlLAQ+5z+J7AjQ+J2d
          dK514JOjxjzJwmhZChndTjNL47dAbYHIJZxbTM6moTh8T/+TyGY=
          -----END RSA PRIVATE KEY-----
        ca: |
          -----BEGIN CERTIFICATE-----
          MIIFUzCCAzugAwIBAgIUGfpxaumpt2PF62TT2fDJV5DvfH0wDQYJKoZIhvcNAQEL
          BQAwOTETMBEGA1UECgwKb3JhbmdlLmNvbTEiMCAGA1UEAwwZcmVkaXMtc2VudGlu
          ZWwtc2hhcmVkLXRsczAeFw0yMDA5MTAxMTE5MzFaFw0zMDA5MDgxMTE5MzFaMDkx
          EzARBgNVBAoMCm9yYW5nZS5jb20xIjAgBgNVBAMMGXJlZGlzLXNlbnRpbmVsLXNo
          YXJlZC10bHMwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQC/Fkl+u4iU
          Hv3FpHnQoGVQE8p+vuPYorECZ6T2AjN+o0cGERuKIqGxNoxN3keltcCtN451fvid
          K9j3epDUPp3RRKoqInqq+uQtwLpUXexdpmnYJ8uZUdc8jSzrc0gv9uZetw/tHNBU
          CGKKwd44+Q5Zet9QPglsQvOKU/cZEUCw+a3ORzXzelXxr3nuMbBUyUQtUpqpHDEl
          QViddjjTBDCmVpP6grYsyteHzVoL6k5kDf+2V7kssQbDepCWsqjKhz+Tkaa3bPq1
          iIpIIFDAYK+HX3lIFYrPrBobd0e47He1qSAzxoGCWyNzqciukzKB5KT5E5/LybNx
          v4rH84xIkRZGViA/P0AgM4NmfjTCA/RizU8C9VJQc9lwsV9GftiG0Rd2ooL9sI6E
          bY9QKbo5qlw3EBwsjcXHM1zGQXBM6/Ps1f83Cr73E/jlzPvyWBm7FBz/NNepy6Gp
          MClZWp7BF1+O68dpF07uZF0GheAPhup2eRoDBIA3XzEzfcnbbFwGu4mUEOmhQSC5
          TUxIKUUyvt+GBJxOtbgxnqc/teTuHdGQM31nMfLO5cI+xlymBB47qyjxww7NjXiP
          jwCvtFwNE79SNYlGxQHGhY2vKEr8lPhfauFQvdIGmGQUhdf6vU/9ppErBzvz7aPN
          IC0xn53Zl+DyTIwQhCdMxT1LUzfOtSLw9wIDAQABo1MwUTAdBgNVHQ4EFgQUo9s4
          8M+ZGMEYFzxONvBxDuNsXBMwHwYDVR0jBBgwFoAUo9s48M+ZGMEYFzxONvBxDuNs
          XBMwDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAgEAi3ZvWAsMly9y
          2xHNwc7KfUGN2nSK6ssCwnz+Ni9lAGbHzn0/byqfnfT0pghqtfp7mD0sYvpkKv9+
          iI47hKoJ7xwcvKXGnWORBHMqEIdiZwxynm+w06/NU1bDfYyt1YZkqiAxIoYu6EUS
          ItyDBsSM/2DYNsv+OyF5zyhH9MjPdSGORW4TWrED00JiydRXV9Q3vDb1SW+o6CDO
          /PWitlgY3ssMmKmrFaQzCvv/Y/w4WMyyywty6+vnXcO1KXyDfCB2MnjEe326CAtZ
          2LsxCRUOJdDqTjEreDuXbBmiOsI1m9p1UYihHbQCuWVV10vGlU0+rLn19PTne6BS
          F9EOsMoTzkd+5OUK09H18Fw677fONpZ0PeufJSLE3BM8OsoYVaCRPsFsnJst9VH4
          BWYoSsIQYOFav9zA4u55jnrNkKFt6moaIrtkuqJKDOUTnnkAUDwjTn+QN22OcRmH
          Eyh4E2hdyTPYM1csPOSkMsOleNMohxk+1oXCWswMeqvTe5zeNPdJ5+ogoZS7j7tm
          IGNHgNcC5Wfi2eT+fKsDdKBCgeK+XMTmOjUtRle+h+Q3O7T74U5NexVrHf+R10K7
          DflJPxUrSbxH0phFgxqKFykhcQfEXzLan/th+B1cnp2+y2kIpNpkxUnRGAh+iKtL
          PTDhxGQ3hAlmpK4bZK8DXEBYIsiGRCM=
          -----END CERTIFICATE-----

variables:
- name: redis_sentinel_password
  type: password
  parameters:
    length: ((password_length))
- name: ((shared_sentinel_ca))
  type: certificate
  options:
    common_name: ((deployment_name))
    organization: 'orange.com'
    key_length: ((ca_key_length))
    duration: ((certificate_duration))
    is_ca: true
    self_sign: true
- name: redis_sentinel_master_keys
  type: certificate
  options:
    ca: ((shared_sentinel_ca))
    common_name: 'Sentinel'
    organization: 'orange.com'
    organization_unit: ((deployment_name))
    key_length: ((private_key_length))
    duration: ((certificate_duration))
- name: redis_sentinel_slave_keys
  type: certificate
  options:
    ca: ((shared_sentinel_ca))
    common_name: 'Sentinel'
    organization: 'orange.com'
    organization_unit: ((deployment_name))
    key_length: ((private_key_length))
    duration: ((certificate_duration))

stemcells:
- alias: default
  os: ((stemcell_os))
  version: "((stemcell_version))"

releases:
- name: redis-service
  version: latest

update:
  canaries: 2
  canary_watch_time: 60000-120000
  max_in_flight: 2
  update_watch_time: 60000-120000
  serial: false
