---
name: ((deployment_name))

instance_groups:
- name: sentinel-master
  azs: [((default_az))]
  instances: ((master_node_count))
  vm_type: ((default_vm_type))
  stemcell: default
  persistent_disk_type: ((default_persistent_disk_type))
  networks:
  - name: ((default_network))
  jobs:
  - name: redis_sentinel
    release: redis-service
    provides:
      redis_sentinel_conn: {as: ((shared_sentinel_master)), shared: true}
    consumes:
      redis_sentinel_conn: {from: ((shared_sentinel_master))}
    properties:
      shared: true
      bind: true
      port: '26389'
      password: ((redis_sentinel_password))
      tls: true
      tls_port: '26379'
      tls_keys: ((redis_sentinel_master_keys))
      tls_replication: true
  - name: redis_sentinel_exporter
    release: redis-service
    consumes:
      redis_sentinel_conn: {from: ((shared_sentinel_master))}
- name: sentinel-slave
  azs: [((default_az))]
  instances: ((slave_node_count))
  vm_type: ((default_vm_type))
  stemcell: default
  persistent_disk_type: ((default_persistent_disk_type))
  networks:
  - name: ((default_network))
  jobs:
  - name: redis_sentinel
    release: redis-service
    provides:
      redis_sentinel_conn: {as: ((shared_sentinel_slave)), shared: true}
    consumes:
      redis_sentinel_conn: {from: ((shared_sentinel_master))}
    properties:
      tls_keys: ((redis_sentinel_slave_keys))
  - name: redis_sentinel_exporter
    release: redis-service
    consumes:
      redis_sentinel_conn: {from: ((shared_sentinel_master))}

variables:
- name: redis_sentinel_password
  type: password
  parameters:
    length: ((password_length))
- name: ((shared_sentinel_ca))
  type: certificate
  options:
    common_name: ((deployment_name))
    organization: 'orange.com'
    key_length: ((ca_key_length))
    duration: ((certificate_duration))
    is_ca: true
    self_sign: true
- name: redis_sentinel_master_keys
  type: certificate
  options:
    ca: ((shared_sentinel_ca))
    common_name: 'Sentinel'
    organization: 'orange.com'
    organization_unit: ((deployment_name))
    key_length: ((private_key_length))
    duration: ((certificate_duration))
- name: redis_sentinel_slave_keys
  type: certificate
  options:
    ca: ((shared_sentinel_ca))
    common_name: 'Sentinel'
    organization: 'orange.com'
    organization_unit: ((deployment_name))
    key_length: ((private_key_length))
    duration: ((certificate_duration))

stemcells:
- alias: default
  os: ((stemcell_os))
  version: "((stemcell_version))"

releases:
- name: redis-service
  version: latest

update:
  canaries: 2
  canary_watch_time: 60000-120000
  max_in_flight: 2
  update_watch_time: 60000-120000
  serial: false
