---
name: ((deployment_name))

instance_groups:
- name: redis-master
  azs: [((default_az))]
  instances: ((master_node_count))
  vm_type: ((default_vm_type))
  stemcell: default
  persistent_disk_type: ((default_persistent_disk_type))
  networks:
  - name: ((default_network))
  jobs:
  - name: redis
    release: redis-service
    consumes:
      redis_sentinel_conn: nil
    properties:
      bind: ((redis_bind))
      port: '0'
      password: ((redis_password))
      admin_password: ((redis_admin_password))
      exporter_password: ((redis_exporter_password))
      maxmemory: ((redis_maxmemory))
      maxmemory_policy: ((redis_maxmemory_policy))
      replication: true
      replica_password: ((redis_replica_password))
      sentinel_password: ((redis_sentinel_user_password))
      tls: true
      tls_keys: ((redis_keys))
      tls_replication: true
  - name: redis_check
    release: redis-service
    consumes:
      redis_sentinel_conn: {from: sentinel_master}
      sentinel_slave_conn: {from: sentinel_slave}
    properties:
      tls_keys: ((redis_check_keys))
  - name: redis_exporter
    release: redis-service
    properties:
      tls_keys: ((redis_exporter_keys))
  - name: redis_sentinel
    release: redis-service
    provides:
      redis_sentinel_conn: {as: sentinel_master}
    consumes:
      redis_sentinel_conn: {from: sentinel_master}
    properties:
      bind: ((redis_bind))
      port: '26389'
      password: ((redis_sentinel_password))
      tls: true
      tls_port: '26379'
      tls_keys: ((redis_sentinel_master_keys))
      tls_replication: true
  - name: redis_sentinel_exporter
    release: redis-service
- name: sentinel-slave
  azs: [((default_az))]
  instances: ((slave_node_count))
  vm_type: ((default_vm_type))
  stemcell: default
  persistent_disk_type: ((default_persistent_disk_type))
  networks:
  - name: ((default_network))
  jobs:
  - name: redis_sentinel
    release: redis-service
    provides:
      redis_sentinel_conn: {as: sentinel_slave}
    consumes:
      redis_sentinel_conn: {from: sentinel_master}
    properties:
      tls_keys: ((redis_sentinel_master_keys))
  - name: redis_sentinel_exporter
    release: redis-service
    consumes:
      redis_sentinel_conn: {from: sentinel_master}
- name: broker
  azs: [((default_az))]
  instances: 1
  vm_type: ((default_vm_type))
  stemcell: default
  persistent_disk_type: ((default_persistent_disk_type))
  networks:
  - name: ((default_network))
  jobs:
  - name: redis_broker-1.5
    release: redis-service
    consumes:
      redis_sentinel_conn: {from: sentinel_master}
    properties:
      bind: ((redis_bind))
      password: ((redis_broker_password))
      tls_keys: ((redis_broker_keys))
  - name: redis_broker_check-1.5
    release: redis-service
    consumes:
      redis_sentinel_conn: {from: sentinel_master}

variables:
- name: redis_password
  type: password
  parameters:
    length: ((password_length))
- name: redis_admin_password
  type: password
  parameters:
    length: ((password_length))
- name: redis_exporter_password
  type: password
  parameters:
    length: ((password_length))
- name: redis_replica_password
  type: password
  parameters:
    length: ((password_length))
- name: redis_sentinel_user_password
  type: password
  parameters:
    length: ((password_length))
- name: redis_sentinel_password
  type: password
  parameters:
    length: ((password_length))
- name: redis_broker_password
  type: password
  parameters:
    length: ((password_length))
- name: redis_ca
  type: certificate
  options:
    common_name: ((deployment_name))
    organization: 'orange.com'
    key_length: ((ca_key_length))
    duration: ((certificate_duration))
    is_ca: true
    self_sign: true
- name: redis_keys
  type: certificate
  options:
    ca: redis_ca
    common_name: 'Server'
    organization: 'orange.com'
    organization_unit: ((deployment_name))
    key_length: ((private_key_length))
    duration: ((certificate_duration))
- name: redis_check_keys
  type: certificate
  options:
    ca: redis_ca
    common_name: 'Client'
    organization: 'orange.com'
    organization_unit: ((deployment_name))
    key_length: ((private_key_length))
    duration: ((certificate_duration))
- name: redis_broker_keys
  type: certificate
  options:
    ca: redis_ca
    common_name: 'Broker'
    organization: 'orange.com'
    organization_unit: ((deployment_name))
    key_length: ((private_key_length))
    duration: ((certificate_duration))
- name: exporter_keys
  type: certificate
  options:
    ca: redis_ca
    common_name: 'Exporter'
    organization: 'orange.com'
    organization_unit: ((deployment_name))
    key_length: ((private_key_length))
    duration: ((certificate_duration))
- name: redis_sentinel_master_keys
  type: certificate
  options:
    ca: redis_ca
    common_name: 'Sentinel'
    organization: 'orange.com'
    organization_unit: ((deployment_name))
    key_length: ((private_key_length))
    duration: ((certificate_duration))
- name: redis_sentinel_slave_keys
  type: certificate
  options:
    ca: redis_ca
    common_name: 'Sentinel'
    organization: 'orange.com'
    organization_unit: ((deployment_name))
    key_length: ((private_key_length))
    duration: ((certificate_duration))

stemcells:
- alias: default
  os: ((stemcell_os))
  version: "((stemcell_version))"

releases:
- name: redis-service
  version: latest

update:
  canaries: 2
  canary_watch_time: 60000-120000
  max_in_flight: 2
  update_watch_time: 60000-120000
  serial: false
